# Generated by Django 4.0.6 on 2022-11-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
