# Generated by Django 4.0.6 on 2022-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_ticket_reserve_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image_url',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
