# Generated by Django 4.0.6 on 2022-11-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_ticket_lien_cadeau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
    ]
